"""initial_tables

Revision ID: c8fbcb04c0fc
Revises: 
Create Date: 2026-04-01 07:03:06.954720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8fbcb04c0fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_permits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('permit_number', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('building_type', sa.String(length=100), nullable=True),
    sa.Column('permit_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='permitted/in_progress/completed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_number')
    )
    op.create_index('idx_construction_region_date', 'construction_permits', ['region_id', 'permit_date'], unique=False)
    op.create_index(op.f('ix_construction_permits_region_id'), 'construction_permits', ['region_id'], unique=False)
    op.create_table('noise_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('region_type', sa.String(length=20), nullable=False, comment='residential/road_park/main_street'),
    sa.Column('max_noise', sa.Float(), nullable=False),
    sa.Column('min_noise', sa.Float(), nullable=False),
    sa.Column('avg_noise', sa.Float(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'region_type', 'measured_at', name='uk_noise_raw_region_type_date')
    )
    op.create_index('idx_noise_raw_region_date', 'noise_raw', ['region_id', 'measured_at'], unique=False)
    op.create_index(op.f('ix_noise_raw_region_id'), 'noise_raw', ['region_id'], unique=False)
    op.create_table('noise_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('avg_noise', sa.Float(), nullable=False),
    sa.Column('noise_level', sa.String(length=20), nullable=False, comment='quiet/normal/loud/very_loud'),
    sa.Column('noise_color', sa.String(length=10), nullable=False, comment='green/yellow/red/black'),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('real_estate_summary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('naver_link', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'trade_type', name='uk_real_estate_summary_region_type')
    )
    op.create_index(op.f('ix_real_estate_summary_region_id'), 'real_estate_summary', ['region_id'], unique=False)
    op.create_table('real_estate_trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False, comment='sale/jeonse/monthly'),
    sa.Column('building_type', sa.String(length=20), nullable=False, comment='apartment/villa/officetel/house'),
    sa.Column('building_name', sa.String(length=100), nullable=True),
    sa.Column('exclusive_area', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False, comment='만원'),
    sa.Column('monthly_rent', sa.Integer(), nullable=True, comment='월세 만원'),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_region_type_date', 'real_estate_trades', ['region_id', 'trade_type', 'trade_date'], unique=False)
    op.create_index(op.f('ix_real_estate_trades_region_id'), 'real_estate_trades', ['region_id'], unique=False)
    op.alter_column('regions', 'district_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='구 이름',
               existing_nullable=False)
    op.alter_column('regions', 'dong_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='동 이름',
               existing_nullable=False)
    op.alter_column('regions', 'district_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='법정동 코드 5자리',
               existing_nullable=True)
    op.create_index('idx_dong', 'regions', ['dong_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dong', table_name='regions')
    op.alter_column('regions', 'district_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment=None,
               existing_comment='법정동 코드 5자리',
               existing_nullable=True)
    op.alter_column('regions', 'dong_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='동 이름',
               existing_nullable=False)
    op.alter_column('regions', 'district_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='구 이름',
               existing_nullable=False)
    op.drop_index(op.f('ix_real_estate_trades_region_id'), table_name='real_estate_trades')
    op.drop_index('idx_trade_region_type_date', table_name='real_estate_trades')
    op.drop_table('real_estate_trades')
    op.drop_index(op.f('ix_real_estate_summary_region_id'), table_name='real_estate_summary')
    op.drop_table('real_estate_summary')
    op.drop_table('noise_summary')
    op.drop_index(op.f('ix_noise_raw_region_id'), table_name='noise_raw')
    op.drop_index('idx_noise_raw_region_date', table_name='noise_raw')
    op.drop_table('noise_raw')
    op.drop_index(op.f('ix_construction_permits_region_id'), table_name='construction_permits')
    op.drop_index('idx_construction_region_date', table_name='construction_permits')
    op.drop_table('construction_permits')
    # ### end Alembic commands ###
